url:    'https://ishdhand.me'
author: 'Ish Dhand'
markdown: kramdown
description: "Ish Dhand is CEO and co-founder of QC Design, a quantum computing startup that offers software for designing scalable quantum computers."

include:  ['_pages']

safe:     true
timezone: 'America/Toronto'

plugins:
  - jekyll-sitemap
